In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
%matplotlib inline

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [23]:
sms= pd.read_csv('spam.csv', encoding='latin-1')
sms=sms.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)
sms.rename(columns={"v1":"type","v2":"text"},inplace=True)

In [25]:
sms.shape

(5572, 2)

In [26]:
sms.type.unique()

array(['ham', 'spam'], dtype=object)

In [27]:
sms.type.value_counts()

ham     4825
spam     747
Name: type, dtype: int64

In [101]:
sms_corpus = sms['text']
y=sms["type"]
vec1=CountVectorizer(min_df=10)               #10번 이하로 나온 단어는 무시해라
#vec2=TfidfVectorizer(min_df=10, ngram_range(1, 2))
X1=vec1.fit_transform(sms_corpus).toarray()
X2=vec2.fit_transform(sms_corpus).toarray()

In [69]:
X1.shape, y.shape

((5572, 1016), (5572,))

In [70]:
X2.shape, y.shape

((5572, 1016), (5572,))

In [71]:
maxidx =X1[:5].argmax(axis=1)


array([ 92, 460, 862, 728, 391], dtype=int64)

In [76]:
[vec1.get_feature_names()[i] for i in maxidx]

NameError: name 'maxidx' is not defined

In [80]:
vec1.get_feature_names()[X1.sum(axis=0).argmax()]

'to'

In [84]:
#vec1.get_feature_names()

# Machine Learning
-Bayes Algorithm 사용

In [113]:
X_train, X_test, y_train, y_test = train_test_split(X1,y, test_size=0.25)
from sklearn.linear_model import SGDClassifier, LogisticRegression
clf = LogisticRegression
#clf =SGDClassifier()
#clf=GaussianNB()              #model 생성
clf.fit(X_train,y_train)     #train the model
clf.score(X_test, y_test)

TypeError: fit() missing 1 required positional argument: 'y'

In [112]:
X_train, X_test, y_train, y_test = train_test_split(X2,y, test_size=0.25)
clf=GaussianNB()              #model 생성
clf.fit(X_train,y_train)     #train the model
clf.score(X_test, y_test)

0.8205312275664034

In [107]:
y_pred = clf.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[971 251]
 [ 12 159]]
              precision    recall  f1-score   support

         ham       0.99      0.79      0.88      1222
        spam       0.39      0.93      0.55       171

    accuracy                           0.81      1393
   macro avg       0.69      0.86      0.71      1393
weighted avg       0.91      0.81      0.84      1393



# CountVectorizer 연습

In [49]:
corpus=[
    'This is the first document,',
    'This document is the second one',
    'And this is the third ond',
    'Is this the first document?'
]

vec1=CountVectorizer()
vec2=TfidfVectorizer()
XX1=vec1.fit_transform(corpus)
XX2=vec2.fit_transform(corpus)

In [50]:
XX1.toarray()

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [51]:
vec1.get_feature_names()

['and',
 'document',
 'first',
 'is',
 'ond',
 'one',
 'second',
 'the',
 'third',
 'this']

In [53]:
XX2.toarray().round(2)

array([[0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.  , 0.38, 0.  , 0.38],
       [0.  , 0.36, 0.  , 0.29, 0.  , 0.56, 0.56, 0.29, 0.  , 0.29],
       [0.51, 0.  , 0.  , 0.27, 0.51, 0.  , 0.  , 0.27, 0.51, 0.27],
       [0.  , 0.47, 0.58, 0.38, 0.  , 0.  , 0.  , 0.38, 0.  , 0.38]])

In [54]:
vec2.get_feature_names()

['and',
 'document',
 'first',
 'is',
 'ond',
 'one',
 'second',
 'the',
 'third',
 'this']